export const labTokenDefinitions = {
  appTitleFontSize: {
    cssName: "--app-title-font-size",
    label: "Title font size",
    min: 12,
    max: 40,
    step: 1,
    unit: "px",
    defaultValue: 16,
  },
} as const;

export type LabTokenName = keyof typeof labTokenDefinitions;
export type LabTokenValues = Record<LabTokenName, number>;

export const defaultLabTokenValues: LabTokenValues = {
  appTitleFontSize: labTokenDefinitions.appTitleFontSize.defaultValue,
};

export function parseLabTokenValues(input: unknown): LabTokenValues | null {
  if (!isRecord(input)) {
    return null;
  }

  const names = Object.keys(labTokenDefinitions) as LabTokenName[];
  if (Object.keys(input).some((name) => !names.includes(name as LabTokenName))) {
    return null;
  }

  const values = { ...defaultLabTokenValues };

  for (const name of names) {
    const value = input[name];
    const definition = labTokenDefinitions[name];

    if (
      typeof value !== "number"
      || !Number.isFinite(value)
      || value < definition.min
      || value > definition.max
      || !isOnStep(value, definition.min, definition.step)
    ) {
      return null;
    }

    values[name] = value;
  }

  return values;
}

export function renderLabTokens(values: LabTokenValues): string {
  const declarations = (Object.keys(labTokenDefinitions) as LabTokenName[])
    .map((name) => {
      const definition = labTokenDefinitions[name];
      return `  ${definition.cssName}: ${values[name]}${definition.unit};`;
    })
    .join("\n");

  return `/* Generated by the development-only component lab. */\n:root {\n${declarations}\n}\n`;
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

function isOnStep(value: number, min: number, step: number): boolean {
  const steps = (value - min) / step;
  return Math.abs(steps - Math.round(steps)) < Number.EPSILON;
}
