export const colorDefinitions = {
  page: { cssName: "--color-page", label: "Page", defaultValue: "#b9b9b9ff" },
  app: { cssName: "--color-app", label: "App", defaultValue: "#eeeeebff" },
  text: { cssName: "--color-text", label: "Text", defaultValue: "#181818ff" },
  textMuted: {
    cssName: "--color-text-muted",
    label: "Text muted",
    defaultValue: "#626262ff",
  },
  border: { cssName: "--color-border", label: "Border", defaultValue: "#888888ff" },
  surface: { cssName: "--color-surface", label: "Surface", defaultValue: "#ffffffff" },
  item: { cssName: "--item-color", label: "Item", defaultValue: "#d3ceb3ff" },
  accentOne: {
    cssName: "--color-accent-one",
    label: "Accent one",
    defaultValue: "#2468b2ff",
  },
  accentTwo: {
    cssName: "--color-accent-two",
    label: "Accent two",
    defaultValue: "#287a3fff",
  },
  speech: {
    cssName: "--color-speech",
    label: "Speech input",
    defaultValue: "#f2b36fff",
  },
  success: { cssName: "--color-success", label: "Success", defaultValue: "#287a3fff" },
  error: { cssName: "--color-error", label: "Error", defaultValue: "#a52b2bff" },
} as const;

export const greyscaleColorValues: ColorValues = {
  page: "#b9b9b9ff",
  app: "#eeeeeeff",
  text: "#181818ff",
  textMuted: "#626262ff",
  border: "#888888ff",
  surface: "#ffffffff",
  item: "#dddddaff",
  accentOne: "#555555ff",
  accentTwo: "#777777ff",
  speech: "#f2b36fff",
  success: "#707070ff",
  error: "#303030ff",
};

export const flydeckV1ColorValues: ColorValues = {
  page: "#beb7c4ff",
  app: "#fff1caff",
  text: "#182026ff",
  textMuted: "#6d7a7aff",
  border: "#8c9a9aff",
  surface: "#ffd151ff",
  item: "#d9e1dfff",
  accentOne: "#4da5dbff",
  accentTwo: "#58b957ff",
  speech: "#f2b36fff",
  success: "#58b957ff",
  error: "#fc512bff",
};

export const themeColorMaps = [
  { id: "flydeck", label: "Flydeck V2" },
  { id: "flydeck-v1", label: "Flydeck V1" },
  { id: "greyscale", label: "Greyscale" },
] as const;

export type ThemeColorMapId = typeof themeColorMaps[number]["id"];

export type ColorName = keyof typeof colorDefinitions;
export type ColorValues = Record<ColorName, string>;
export type ThemeConfig = {
  activeTheme: ThemeColorMapId;
  themes: Record<ThemeColorMapId, ColorValues>;
  tokens: Record<ThemeColorMapId, LabTokenValues>;
};

export const defaultColorValues: ColorValues = Object.fromEntries(
  (Object.keys(colorDefinitions) as ColorName[])
    .map((name) => [name, colorDefinitions[name].defaultValue]),
) as ColorValues;

export function parseColorValues(input: unknown): ColorValues | null {
  if (typeof input !== "object" || input === null || Array.isArray(input)) {
    return null;
  }

  const record = input as Record<string, unknown>;
  const names = Object.keys(colorDefinitions) as ColorName[];
  if (
    Object.keys(record).length !== names.length
    || Object.keys(record).some((name) => !names.includes(name as ColorName))
  ) {
    return null;
  }

  const values = {} as ColorValues;
  for (const name of names) {
    const value = record[name];
    if (typeof value !== "string" || !/^#[0-9a-f]{8}$/i.test(value)) {
      return null;
    }
    values[name] = value.toLowerCase();
  }

  return values;
}

export function renderColors(values: ColorValues): string {
  const declarations = (Object.keys(colorDefinitions) as ColorName[])
    .map((name) => `  ${colorDefinitions[name].cssName}: ${values[name]};`)
    .join("\n");

  return `/* Generated by the development-only component lab. */\n:root {\n${declarations}\n}\n`;
}

export function parseThemeConfig(input: unknown): ThemeConfig | null {
  if (typeof input !== "object" || input === null || Array.isArray(input)) {
    return null;
  }

  const record = input as Record<string, unknown>;
  const activeTheme = record.activeTheme;
  const themes = record.themes;
  const tokens = record.tokens;
  const themeIds = themeColorMaps.map((theme) => theme.id);

  if (
    typeof activeTheme !== "string"
    || !themeIds.includes(activeTheme as ThemeColorMapId)
    || typeof themes !== "object"
    || themes === null
    || Array.isArray(themes)
    || typeof tokens !== "object"
    || tokens === null
    || Array.isArray(tokens)
  ) {
    return null;
  }

  const themeRecord = themes as Record<string, unknown>;
  const tokenRecord = tokens as Record<string, unknown>;
  if (
    Object.keys(themeRecord).length !== themeIds.length
    || Object.keys(themeRecord).some((id) => !themeIds.includes(id as ThemeColorMapId))
    || Object.keys(tokenRecord).length !== themeIds.length
    || Object.keys(tokenRecord).some((id) => !themeIds.includes(id as ThemeColorMapId))
  ) {
    return null;
  }

  const parsedThemes = {} as Record<ThemeColorMapId, ColorValues>;
  const parsedTokens = {} as Record<ThemeColorMapId, LabTokenValues>;
  for (const id of themeIds) {
    const values = parseColorValues(themeRecord[id]);
    const tokenValues = parseLabTokenValues(tokenRecord[id]);
    if (!values || !tokenValues) {
      return null;
    }
    parsedThemes[id] = values;
    parsedTokens[id] = tokenValues;
  }

  return {
    activeTheme: activeTheme as ThemeColorMapId,
    themes: parsedThemes,
    tokens: parsedTokens,
  };
}
import {
  parseLabTokenValues,
  type LabTokenValues,
} from "../lab/tokenDefinitions";
