export {
  Base,
  BaseConfigurationProvider,
  collectComponentNames,
  type BaseConfigurationProviderProps,
  baseBackgrounds,
  baseBorders,
  baseColors,
  baseSizes,
  baseSpaces,
  resolveCssValue,
  type BaseBackground,
  type BaseBorder,
  type BaseColor,
  type BaseProps,
  type BaseSpace,
  type BaseStyleProps,
} from "./Base";
