export {
  InputAids,
  copySelection,
  formatDate,
  formatTime,
  expandedWordRange,
  moveCursor,
  pasteSelection,
  insertCurrentDate,
  insertCurrentTime,
  replaceSelection,
  selectAll,
  selectWordAtCursor,
  scaledFontSize,
  wordRangeAtCursor,
  type InputAidsProps,
  type InputFontStage,
  type TextEntryElement,
} from "./InputAids";
